/**
 * Real last-change date of each public page, read from src/data/lastmod.json.
 * That file is generated by scripts/lastmod.mjs from full git history and
 * committed, so a shallow build clone cannot falsify it.
 */
import dates from '@/data/lastmod.json';

const map = dates as Record<string, string>;

export function siteLastModified(): string {
  return Object.values(map).sort().pop() ?? '2026-09-04T00:00:00+00:00';
}

export function pageLastModified(pathname: string): string {
  return map[pathname] ?? siteLastModified();
}
