/**
 * Copies the built MCP discovery document (dist/mcp.json, generated from
 * src/data) into api/_card.js, the data module of the MCP server.
 *
 * Runs after `astro build`. It writes only from a production-mode build (a
 * real https origin): a protected local build carries a placeholder origin,
 * and writing it would put a wrong Origin allow-list into the server. The
 * audit then refuses to ship a copy that differs from the document.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';

const card = JSON.parse(readFileSync('dist/mcp.json', 'utf8'));
if (/\.invalid|localhost|127\.0\.0\.1/.test(card.site)) {
  console.log('mcp-sync: protected build (' + card.site + '), keeping the committed api/_card.js.');
  process.exit(0);
}

const out =
  '/* Generated by scripts/mcp-sync.mjs from dist/mcp.json. Do not edit: change src/data instead. */\n' +
  'export default ' + JSON.stringify(card, null, 2) + ';\n';
const before = existsSync('api/_card.js') ? readFileSync('api/_card.js', 'utf8') : '';
writeFileSync('api/_card.js', out);
console.log(
  'mcp-sync: api/_card.js ' + (before === out ? 'unchanged' : 'updated') + ' (' +
  card.facts.pages.length + ' pages, ' + card.facts.courses.length + ' courses, ' + card.facts.network.length + ' network clubs).'
);
