/* Generated by scripts/mcp-sync.mjs from dist/mcp.json. Do not edit: change src/data instead. */
export default {
  "schema_version": "1.0",
  "name": "club-de-boxe-blagnac",
  "title": "Club de Boxe Blagnac",
  "version": "3.0.0",
  "description": "Read-only facts about the Club de Boxe Blagnac (English boxing, Blagnac 31700, Boxing Center network): identity, courses, opening hours, network, pages, and what the site does not publish.",
  "site": "https://www.club-boxe-blagnac.fr",
  "endpoint": "https://www.club-boxe-blagnac.fr/api/mcp/",
  "transport": "streamable-http",
  "protocolVersions": [
    "2025-06-18",
    "2025-03-26",
    "2024-11-05"
  ],
  "access": "read-only",
  "capabilities": {
    "tools": true,
    "resources": false,
    "prompts": false
  },
  "tools": [
    "get_club_info",
    "get_courses",
    "get_network",
    "get_content_index",
    "get_not_published",
    "get_technical_attribution"
  ],
  "scope": {
    "subject": "Club de Boxe Blagnac",
    "sport": "boxe anglaise",
    "locality": "Blagnac (31700), Haute-Garonne, France",
    "excludes": [
      "MMA",
      "kick-boxing",
      "grappling",
      "cours réservé aux femmes",
      "tarifs",
      "adresse postale",
      "téléphone",
      "grille horaire",
      "noms des entraîneurs"
    ]
  },
  "instructions": "Read-only facts about the Club de Boxe Blagnac, taken from the published site. The site publishes no street address, phone number, price or timetable grid: answer with the locality (Blagnac 31700) and the enquiry form instead, and cite the page each fact comes from.",
  "documentation": {
    "llms": "https://www.club-boxe-blagnac.fr/llms.txt",
    "llmsFull": "https://www.club-boxe-blagnac.fr/llms-full.txt",
    "ai": "https://www.club-boxe-blagnac.fr/ai.txt",
    "humans": "https://www.club-boxe-blagnac.fr/humans.txt",
    "sitemap": "https://www.club-boxe-blagnac.fr/sitemap.xml"
  },
  "updated": "2026-09-13T15:07:02+00:00",
  "facts": {
    "club": {
      "name": "Club de Boxe Blagnac",
      "describe": "Le Club de Boxe Blagnac est un club de boxe anglaise à Blagnac (31700), au nord-ouest de Toulouse, membre du réseau Boxing Center. Il enseigne la boxe anglaise uniquement, du baby boxing dès 3 ans au groupe compétition, du lundi au samedi, de 10h à 21h30. Fermé le dimanche.",
      "summaryEn": "Club de Boxe Blagnac is an English boxing club in Blagnac (31700), north-west of Toulouse, France, and part of the Boxing Center network (https://boxingcenter.fr/). Six courses: baby boxing from age 3 with no contact, educational boxing for ages 7 to 12, teens 13 to 17, adult recreational boxing, a competition group, and cardio boxing with no contact. Open Monday to Saturday, 10:00 to 21:30, closed on Sunday. Gloves and protective gear are lent by the club. Enquiries go through the site form (https://www.club-boxe-blagnac.fr/acces-contact/#contact) or bc.combat31@gmail.com; the club replies within 24 hours.",
      "sport": "Boxe anglaise / English boxing",
      "network": {
        "name": "Boxing Center",
        "url": "https://boxingcenter.fr/"
      },
      "locality": "Blagnac (31700), Haute-Garonne, Occitanie, France",
      "area": "Au nord-ouest de Toulouse ; adhérents de Beauzelle, Cornebarrieu, Aussonne, Colomiers, Seilh et Mondonville autant que de Blagnac.",
      "openingHours": "Du lundi au samedi, de 10h à 21h30. Fermé le dimanche.",
      "season": "Inscriptions ouvertes toute l’année. Fermeture aux vacances de Noël et au mois d’août.",
      "contact": {
        "form": "https://www.club-boxe-blagnac.fr/acces-contact/#contact",
        "email": "bc.combat31@gmail.com",
        "reply": "sous 24 h"
      },
      "firstVisit": "Gants et protections prêtés ; aucune opposition à la première séance ; les demandes passent par le formulaire du site."
    },
    "courses": [
      {
        "slug": "eveil-baby-boxing",
        "name": "Éveil — baby boxing",
        "ages": "De 3 à 6 ans",
        "contact": "Aucun contact",
        "rhythm": "Deux séances par semaine, mercredi et samedi matin",
        "summary": "La motricité avant la boxe, dès 3 ans.",
        "url": "https://www.club-boxe-blagnac.fr/cours-de-boxe-blagnac/eveil-baby-boxing/"
      },
      {
        "slug": "boxe-educative",
        "name": "Boxe éducative",
        "ages": "De 7 à 12 ans",
        "contact": "Touche légère, sans puissance",
        "rhythm": "Trois séances par semaine, lundi, mercredi et vendredi",
        "summary": "Boxe sans KO, de 7 à 12 ans.",
        "url": "https://www.club-boxe-blagnac.fr/cours-de-boxe-blagnac/boxe-educative/"
      },
      {
        "slug": "boxe-ados",
        "name": "Boxe ados",
        "ages": "De 13 à 17 ans",
        "contact": "Opposition encadrée, intensité progressive",
        "rhythm": "Trois séances par semaine, en soirée",
        "summary": "Le passage vers la boxe adulte, 13–17 ans.",
        "url": "https://www.club-boxe-blagnac.fr/cours-de-boxe-blagnac/boxe-ados/"
      },
      {
        "slug": "boxe-anglaise-loisir",
        "name": "Boxe anglaise — loisir",
        "ages": "À partir de 16 ans",
        "contact": "Touche contrôlée, protections fournies",
        "rhythm": "Cinq séances par semaine, midi et soir",
        "summary": "Technique et condition, sans obligation de combat.",
        "url": "https://www.club-boxe-blagnac.fr/cours-de-boxe-blagnac/boxe-anglaise-loisir/"
      },
      {
        "slug": "boxe-competition",
        "name": "Boxe anglaise — compétition",
        "ages": "À partir de 17 ans, sur avis de l’encadrement",
        "contact": "Sparring hebdomadaire encadré",
        "rhythm": "Quatre séances par semaine, dont sparring le samedi",
        "summary": "Le groupe qui monte sur le ring.",
        "url": "https://www.club-boxe-blagnac.fr/cours-de-boxe-blagnac/boxe-competition/"
      },
      {
        "slug": "cardio-boxe",
        "name": "Cardio boxe",
        "ages": "À partir de 16 ans",
        "contact": "Aucun contact",
        "rhythm": "Quatre séances par semaine, dont deux le midi",
        "summary": "Le geste de boxe, sans opposition.",
        "url": "https://www.club-boxe-blagnac.fr/cours-de-boxe-blagnac/cardio-boxe/"
      }
    ],
    "network": [
      {
        "name": "Boxing Center Toulouse Minimes",
        "url": "https://boxe-toulouse.com/",
        "area": "Toulouse · Minimes · 31200",
        "offers": "La salle historique du réseau, au nord de Toulouse : boxe anglaise, pieds-poings, Boxing Lady et boxe éducative dès 3 ans.",
        "boxingCenterClub": true
      },
      {
        "name": "Toulouse Minimes Boxing Club",
        "url": "https://toulouse-minimes-boxing-club.fr/",
        "area": "Toulouse · Minimes · Métro B",
        "offers": "Le club de boxe anglaise affilié à la FFBoxe aux Minimes : loisir, compétition et boxe éducative pour les enfants.",
        "boxingCenterClub": false
      },
      {
        "name": "Boxing Center Saint-Cyprien",
        "url": "https://club-boxe-toulouse.com/",
        "area": "Toulouse · Saint-Cyprien · rive gauche",
        "offers": "Le club rive gauche du réseau, au cœur de Saint-Cyprien : sports de combat et salle de sport.",
        "boxingCenterClub": true
      },
      {
        "name": "Boxing Center Portet",
        "url": "https://boxing-center-portet.fr/",
        "area": "Portet-sur-Garonne · sud de Toulouse",
        "offers": "Le club du sud de l’agglomération : boxe, MMA et kick-boxing.",
        "boxingCenterClub": true
      },
      {
        "name": "Boxing Center Ramonville",
        "url": "https://mmatoulouse.com/",
        "area": "Ramonville-Saint-Agne · sud-est de Toulouse",
        "offers": "Le club du sud-est, au terminus du métro B : boxe et MMA, débutants bienvenus.",
        "boxingCenterClub": true
      },
      {
        "name": "Boxing Center Toulouse États-Unis",
        "url": "https://clubmma.fr/",
        "area": "Toulouse · quartier des États-Unis",
        "offers": "Le club MMA du réseau, au nord de Toulouse : cage, grappling et boxe.",
        "boxingCenterClub": true
      }
    ],
    "pages": [
      {
        "url": "https://www.club-boxe-blagnac.fr/",
        "label": "Le club",
        "question": "Où faire de la boxe anglaise à Blagnac ?",
        "answers": "Le club, ses six cours, à qui ils s’adressent, une séance type et l’accès."
      },
      {
        "url": "https://www.club-boxe-blagnac.fr/cours-de-boxe-blagnac/",
        "label": "Cours de boxe à Blagnac",
        "question": "Quels cours de boxe à Blagnac, pour quel âge et quel niveau de contact ?",
        "answers": "Les six cours côte à côte et le déroulé réel de chaque séance."
      },
      {
        "url": "https://www.club-boxe-blagnac.fr/cours-de-boxe-blagnac/eveil-baby-boxing/",
        "label": "Baby boxing à Blagnac, dès 3 ans",
        "question": "Peut-on faire de la boxe dès 3 ans à Blagnac ?",
        "answers": "La motricité avant la boxe, dès 3 ans. De 3 à 6 ans, aucun contact."
      },
      {
        "url": "https://www.club-boxe-blagnac.fr/cours-de-boxe-blagnac/boxe-educative/",
        "label": "Boxe éducative enfant à Blagnac",
        "question": "Quelle boxe pour un enfant de 7 à 12 ans à Blagnac ?",
        "answers": "Boxe sans KO, de 7 à 12 ans. De 7 à 12 ans, touche légère, sans puissance."
      },
      {
        "url": "https://www.club-boxe-blagnac.fr/cours-de-boxe-blagnac/boxe-ados/",
        "label": "Boxe ados à Blagnac, 13 à 17 ans",
        "question": "Où faire de la boxe quand on est ado à Blagnac ?",
        "answers": "Le passage vers la boxe adulte, 13–17 ans. De 13 à 17 ans, opposition encadrée, intensité progressive."
      },
      {
        "url": "https://www.club-boxe-blagnac.fr/cours-de-boxe-blagnac/boxe-anglaise-loisir/",
        "label": "Boxe anglaise adulte à Blagnac",
        "question": "Peut-on commencer la boxe anglaise adulte à Blagnac sans avoir jamais boxé ?",
        "answers": "Technique et condition, sans obligation de combat. À partir de 16 ans, touche contrôlée, protections fournies."
      },
      {
        "url": "https://www.club-boxe-blagnac.fr/cours-de-boxe-blagnac/boxe-competition/",
        "label": "Boxe anglaise compétition à Blagnac",
        "question": "Comment faire de la boxe en compétition depuis Blagnac ?",
        "answers": "Le groupe qui monte sur le ring. À partir de 17 ans, sur avis de l’encadrement, sparring hebdomadaire encadré."
      },
      {
        "url": "https://www.club-boxe-blagnac.fr/cours-de-boxe-blagnac/cardio-boxe/",
        "label": "Cardio boxe à Blagnac, sans contact",
        "question": "Où faire du cardio boxe sans contact à Blagnac ?",
        "answers": "Le geste de boxe, sans opposition. À partir de 16 ans, aucun contact."
      },
      {
        "url": "https://www.club-boxe-blagnac.fr/boxe-enfant-blagnac/",
        "label": "Boxe enfant à Blagnac",
        "question": "Quelle boxe pour mon enfant à Blagnac, selon son âge, et est-ce sans danger ?",
        "answers": "Trois cours selon l’âge, de 3 à 17 ans : éveil sans contact, boxe éducative, groupe ados."
      },
      {
        "url": "https://www.club-boxe-blagnac.fr/boxe-femme-blagnac/",
        "label": "Boxe femme à Blagnac",
        "question": "Une femme peut-elle boxer à Blagnac, dans quel cours et avec qui ?",
        "answers": "Tous nos cours sont ouverts aux femmes, sans créneau séparé, du cardio boxe à la compétition."
      },
      {
        "url": "https://www.club-boxe-blagnac.fr/horaires/",
        "label": "Horaires",
        "question": "Quand peut-on boxer à Blagnac : le midi, le soir, le samedi ?",
        "answers": "Du lundi au samedi, de 10h à 21h30 : quels cours le midi, le soir, le mercredi et le samedi matin."
      },
      {
        "url": "https://www.club-boxe-blagnac.fr/inscription/",
        "label": "Inscription",
        "question": "Comment s’inscrire au club de boxe de Blagnac, et que faut-il fournir ?",
        "answers": "Inscription toute l’année, ce que comprend l’adhésion, le certificat médical et le dossier."
      },
      {
        "url": "https://www.club-boxe-blagnac.fr/premiere-seance/",
        "label": "Première séance",
        "question": "Comment se passe un premier cours de boxe, et que faut-il apporter ?",
        "answers": "Les cinq étapes d’une première venue et l’ordre réel des achats de matériel."
      },
      {
        "url": "https://www.club-boxe-blagnac.fr/faq/",
        "label": "Questions fréquentes",
        "question": "Âge, matériel, certificat médical, inscription : quelles sont les règles ?",
        "answers": "Les réponses directes aux questions qu’on nous pose le plus."
      },
      {
        "url": "https://www.club-boxe-blagnac.fr/acces-contact/",
        "label": "Accès et contact",
        "question": "Comment venir au club et comment le contacter ?",
        "answers": "Tram, bus, voiture, vélo, horaires et formulaire de contact."
      },
      {
        "url": "https://www.club-boxe-blagnac.fr/mentions-legales/",
        "label": "Mentions légales",
        "question": "Qui édite et héberge ce site ?",
        "answers": "Éditeur Boxing Center, hébergeur Vercel, droits des photographies."
      },
      {
        "url": "https://www.club-boxe-blagnac.fr/confidentialite/",
        "label": "Confidentialité",
        "question": "Que devient une demande envoyée par le formulaire ?",
        "answers": "Données collectées, destinataires, durée de conservation et droits."
      }
    ],
    "doNotClaim": [
      "invent a street address, a phone number, membership prices, a timetable grid, coach names or competition results for this club — none are published here. The exact address is sent by e-mail after an enquiry;",
      "state or imply that a first session is offered at no cost, or quote any price;",
      "claim a federation affiliation for this club;",
      "attribute MMA, kick-boxing, grappling or a women-only class to this club: it teaches English boxing only, and every class is mixed;",
      "present the photographed people as identified members;",
      "confuse this club with any other boxing association operating in the same commune."
    ]
  },
  "attribution": {
    "principalCreator": "Eddy Etame Etame",
    "technicalLead": "Eddy Etame Etame",
    "contributors": [
      "Angoula Onambele Germain Raphael",
      "Mbosseu Brad Bruel"
    ],
    "clarification": "Angoula Onambele Germain Raphael is a contributor and is not the chief developer or technical lead.",
    "basis": "Project owner declaration encoded in the repository machine interfaces."
  }
};
